# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

truncnorm_lg <- function(y_lower, y_upper, mu, sigma, u_rand) {
    .Call(`_GGIF_truncnorm_lg`, y_lower, y_upper, mu, sigma, u_rand)
}

